# application.yml
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.yandex.com.tr or smtp.gmail.com
    username: your_account@yandex.com
    password: your_password
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
    protocol: smtp
    test-connection: false
server:
  port: 8888